image: alpine:latest

variables:
  DOCKER_IMAGE: sipeai/sipeai
  DOCKER_TAG: latest
  GCP_VM_IP: 34.88.134.163
  SSH_USER: sipeai9
  DEPLOY_DIR: /home/sipeai9/sipe-frontend/

stages:
  - deploy

before_script:
  - apk update && apk add --no-cache openssh-client bash

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $GCP_VM_IP >> ~/.ssh/known_hosts
    - |
      ssh -o StrictHostKeyChecking=no $SSH_USER@$GCP_VM_IP << 'EOF'
      set -e  # Exit on error
      cd $DEPLOY_DIR || { echo "Error: Directory $DEPLOY_DIR does not exist"; exit 1; }
      echo "Current directory: $(pwd)"
      ls -lah  # Debugging: List files in the directory
      if [ ! -f "docker-compose.yml" ]; then
        echo "Error: docker-compose.yml not found in $(pwd)"
        exit 1
      fi
      docker-compose down
      docker pull "$DOCKER_IMAGE:$DOCKER_TAG"
      docker-compose up -d
      EOF
  only:
    - main
