image: google/cloud-sdk:latest

variables:
  GOOGLE_PROJECT_ID: "prismatic-rock-451120-d9"

stages:
  - setup

setup_grit:
  stage: setup
  script:
    - chmod +x grit-setup.sh
    - ./grit-setup.sh --debug
  only:
    - main
