image: google/cloud-sdk:latest

variables:
  PROJECT_ID: "prismatic-rock-451120-d9"
  GCP_REGION: "europe-north1-b"
  GCP_WORKLOAD_IDENTITY_PROVIDER: "principal://iam.googleapis.com/projects/637578382119/locations/global/workloadIdentityPools/gitlab-pool/subject/SUBJECT_ATTRIBUTE_VALUE"
  GCP_SERVICE_ACCOUNT: "gitlab-ci@your-gcp-project-id.iam.gserviceaccount.com"

stages:
  - deploy

before_script:
  - gcloud auth login --brief --impersonate-service-account=$GCP_SERVICE_ACCOUNT

deploy:
  stage: deploy
  script:
    - gcloud auth configure-docker
    - gcloud compute ssh $SSH_USER@$GCP_VM_IP --command="cd $DEPLOY_DIR && docker-compose pull && docker-compose up -d"
  only:
    - main
