services:
  frontend:
    platform: linux/amd64
    image: arifariofficial/sipe:latest
    env_file:
      - .env.production
    networks:
      - sipe-network
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "npx prisma migrate deploy && node server.js"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdataa
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sipe-network
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    networks:
      - sipe-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - sipe-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sipe-network
    restart: unless-stopped
    depends_on:
      - frontend

networks:
  sipe-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
