services:
  frontend:
    platform: linux/amd64
    image: arifariofficial/sipe:latest
    env_file:
      - .env.production
    ports:
      - 3000:3000
    networks:
      - sipe-network
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sipe-network
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    restart: always
    networks:
      - sipe-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sipe-network
    restart: unless-stopped
    depends_on:
      - frontend

  jenkins:
    image: arifariofficial/sipe-jenkins:latest
    user: root
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    ports:
      - "8080:8080"
      - "50000:50000" # For Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/sipeai8/sipe-frontend:/home/sipeai8/sipe-frontend
    networks:
      - sipe-network
    restart: unless-stopped

networks:
  sipe-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  jenkins_home:
    driver: local
