services:
  frontend:
    platform: linux/amd64
    image: arifariofficial/sipe:latest
    env_file:
      - .env.production
    ports:
      - 3000:3000
    networks:
      - sipe-network
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - .env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sipe-network
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    networks:
      - sipe-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sipe-network
    restart: unless-stopped
    depends_on:
      - frontend

networks:
  sipe-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
